# This file contains the fastlane.tools configuration
# You can find the documentation at https://docs.fastlane.tools
#
# For a list of all available actions, check out
#
#     https://docs.fastlane.tools/actions
#
# For a list of all available plugins, check out
#
#     https://docs.fastlane.tools/plugins/available-plugins
#

# Uncomment the line if you want fastlane to automatically update itself
# update_fastlane

default_platform(:ios)

platform :ios do
  desc "Run unit tests"
  lane :unit_test do
    run_tests(
      scheme: "AIClassification",
      device: "iPhone 17 Pro",
      clean: true,                 # Clean before testing
      output_directory: "./fastlane/test_output",
      output_types: "html,junit",
      output_files: "report.html,report.junit",
      disable_concurrent_testing: true
    )
  end
end
